### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rukai** [rukai/treeflection#1]
- [x] Use serde for setting/getting containers
- [x] Index notation/IndexProperty for tuples
- [x] impl more vec like functions onto ContextVec
- [x] Add [?] syntax to command parser
- [x] Index notation/IndexProperty for enum tuples
- [x] Dot notation/ChainProperty for enum structs
- [x] dont explode everytime something goes slightly wrong

**Comment by rukai** [comment]
Moved remaining tasks into seperate issues.
